### ISSUE TITLE
Installing development version of plugin

### ISSUE THREAD

**Issue by HughMacdonald** [eXpl0it3r/streamdeck-clockify#26]
I know I've done this before, but I can't recall how.

I'm using JetBrains Rider for C# development, which supports .sln files.

When I load the solution, I get option for "Publish for Windows" and "Publish for MacOS". I'm on Windows here.

If I run the "Publish for Windows" option, I get the plugin built in `bin\Publish\dev.duerrenberger.clockify.sdPlugin\Windows`. However, there isn't anywhere a plugin file to double click to install.

The contents of the folder is:
![image](https://github.com/user-attachments/assets/e5ddd52f-aaad-49ee-9e4d-80a4e11a0ed3)

How do I install this into StreamDeck for testing?

Thanks

**Comment by eXpl0it3r** [comment]
In the past you needed to get the DistributionTool. Looks like they changed this to the [streamdeck CLI](https://docs.elgato.com/streamdeck/cli/intro) (`npm install -g @elgato/cli@latest`).

You also have to move it into the `Windows` or `macOS` folder or adjust the `manifest.json` to point to the right location.

I'd have suggested to use the GitHub Actions CI pipeline, but since they seem to have changed the approach here, it likely doesn't work anymore.

**Comment by eXpl0it3r** [comment]
The CI still works for now, but I'll eventually have to switch to the CLI or hope the action author does it for me 😄
